index:
    path: /
    controller: App\Controller\GeneralController::accueil

login:
    path: /login
    controller: App\Controller\GeneralController::login

login_guest:
    path: /guest
    controller: App\Controller\GeneralController::guest


