index:
    path: /
    controller: App\Controller\GeneralController::accueil

#login:
#    path: /login
#    controller: App\Controller\GeneralController::login

#logout:
#    path: /logout
#    controller: App\Controller\GeneralController::logout

login_guest:
    path: /guest
    controller: App\Controller\GeneralController::guest

home_admin:
    path: /homeAdmin
    controller: App\Controller\GeneralController::homeAdmin

home_external_speaker:
    path: /homeExternalSpeaker
    controller: App\Controller\GeneralController::homeExternalSpeaker

home_responsable_ue:
    path: /homeRUE
    controller: App\Controller\GeneralController::homeRue

home_scolarite:
    path: /homeScolarite
    controller: App\Controller\GeneralController::homeScolarite

home_students:
    path: /homeStudent
    controller: App\Controller\GeneralController::homeStudents

home_tutors:
    path: /homeTutor
    controller: App\Controller\GeneralController::homeTutors

RUE_see_feasibility_sheet:
    path: /RUE/feasibility
    controller: App\Controller\GeneralController::RUEFeasibility

setting:
    path: /setting
    controller: App\Controller\GeneralController::setting

student_list:
    path: /students
    controller: App\Controller\GeneralController::listStudents

tutor_list:
    path: /tuteurs
    controller: App\Controller\GeneralController::listTutors

tutor_assign:
    path: /tutorAssign
    controller: App\Controller\GeneralController::assignTutor

add_feasibility_sheet:
    path: /addSheet
    controller: App\Controller\GeneralController::addSheet

add_list_students:
    path: /addListStudent
    controller: App\Controller\GeneralController::addListStudent

scolarite_document:
    path: /scolarite/addDocument
    controller: App\Controller\ScolariteController::addDocument

scolarite_students:
    path: /scolarite/students
    controller: App\Controller\ScolariteController::listStudents

student_marks:
    path: /student/marks
    controller: App\Controller\StudentController::marks

student_document:
    path: /student/addDocument
    controller: App\Controller\StudentController::addDocument

external_rateStudent:
    path: /ExternalSpeaker/rateStudent
    controller: App\Controller\ExternalController::rateStudent

tutor_students:
    path: /tutor/students
    controller: App\Controller\TutorController::listStudents

tutor_document:
    path: /tutor/addDocument
    controller: App\Controller\TutorController::addDocument

tutor_rateStudent:
    path: /tutor/rateStudent
    controller: App\Controller\TutorController::rateStudent

error404:
    path: /{url} 
    controller: App\Controller\GeneralController::erreur

