index:
    path: /
    controller: App\Controller\GeneralController::accueil

#login:
#    path: /login
#    controller: App\Controller\GeneralController::login

#logout:
#    path: /logout
#    controller: App\Controller\GeneralController::logout

login_guest:
    path: /guest
    controller: App\Controller\GeneralController::guest

home_admin:
    path: /homeAdmin
    controller: App\Controller\GeneralController::homeAdmin

home_external_speaker:
    path: /homeExternalSpeaker
    controller: App\Controller\GeneralController::homeExternalSpeaker

home_responsable_ue:
    path: /homeRUE
    controller: App\Controller\GeneralController::homeRue

home_scolarite:
    path: /homeScolarite
    controller: App\Controller\GeneralController::homeScolarite

home_students:
    path: /homeStudent
    controller: App\Controller\GeneralController::homeStudents

home_tutors:
    path: /homeTutor
    controller: App\Controller\GeneralController::homeTutors

RUE_add_document:
    path: /RUE/addDocument
    controller: App\Controller\GeneralController::addDocument

RUE_see_feasibility_sheet:
    path: /RUE/feasibility
    controller: App\Controller\GeneralController::RUEFeasibility

RUE_documents:
    path: /RUE/documents
    controller: App\Controller\GeneralController::listDocuments

RUE_download:
    path: /RUE/document/{id}
    controller: App\Controller\GeneralController::downloadDocument
    requirements:
        id:  \d+

RUE_refuse_comment:
    path: /RUE/refuseDocument/{id}
    controller: App\Controller\GeneralController::refuseDocument
    requirements:
        id:  \d+

RUE_admit_comment:
    path: /RUE/admitDocument/{id}
    controller: App\Controller\GeneralController::admitDocument
    requirements:
        id:  \d+

RUE_add_comment:
    path: /RUE/addComment/{id}
    controller: App\Controller\GeneralController::addComment
    requirements:
        id:  \d+

RUE_add_comment_suite:
    path: /RUE/addCommentSuite/{id}
    controller: App\Controller\GeneralController::addCommentSuite
    methods: POST

setting:
    path: /RUE/setting
    controller: App\Controller\GeneralController::setting

RUE_setting:
    path: /RUE/setting/{id}
    controller: App\Controller\GeneralController::editSetting
    requirements:
        id:  \d+

student_list:
    path: /students
    controller: App\Controller\GeneralController::listStudents

tutor_list:
    path: /tuteurs
    controller: App\Controller\GeneralController::listTutors

tutor_comment:
    path: /tuteurs/{id}
    controller: App\Controller\GeneralController::commentTutor
    requirements:
        id:  \d+

tutor_assign:
    path: /tutorAssign
    controller: App\Controller\GeneralController::assignTutor

tutor_affect:
    path: /tutorAssign/{id}
    controller: App\Controller\GeneralController::affectTutor
    requirements:
        id:  \d+

add_feasibility_sheet:
    path: /addSheet
    controller: App\Controller\GeneralController::addSheet

add_list_students:
    path: /addListStudent
    controller: App\Controller\GeneralController::addListStudent

scolarite_document:
    path: /scolarite/addDocument
    controller: App\Controller\ScolariteController::addDocument

scolarite_documents:
    path: /scolarite/documents
    controller: App\Controller\ScolariteController::listDocuments

scolarite_students:
    path: /scolarite/students
    controller: App\Controller\ScolariteController::listStudents

scolarite_download:
    path: /tutor/document/{id}
    controller: App\Controller\ScolariteController::downloadDocument
    requirements:
        id:  \d+

student_marks:
    path: /student/marks
    controller: App\Controller\StudentController::marks

student_document:
    path: /student/addDocument
    controller: App\Controller\StudentController::addDocument

student_documents:
    path: /student/documents
    controller: App\Controller\StudentController::listDocuments

student_download:
    path: /student/document/{id}
    controller: App\Controller\StudentController::downloadDocument
    requirements:
        id:  \d+

external_rateStudent:
    path: /ExternalSpeaker/rateStudent
    controller: App\Controller\ExternalController::rateStudent

tutor_students:
    path: /tutor/students
    controller: App\Controller\TutorController::listStudents

tutor_student:
    path: /tutor/student/{id}
    controller: App\Controller\TutorController::editStudent
    requirements:
        id:  \d+

tutor_document:
    path: /tutor/addDocument
    controller: App\Controller\TutorController::addDocument

tutor_documents:
    path: /tutor/documents
    controller: App\Controller\TutorController::listDocuments

tutor_rateStudent:
    path: /tutor/rateStudent
    controller: App\Controller\TutorController::rateStudent

tutor_download:
    path: /tutor/document/{id}
    controller: App\Controller\TutorController::downloadDocument
    requirements:
        id:  \d+
    
error404:
    path: /{url} 
    controller: App\Controller\GeneralController::erreur

